i18n: add italian translation
lbenie/reading-time-estimator pull request #1613
Opened 2024-09-13 21:12 UTC by stefanobartoletti

I added i18n for italian language.

It should be everything ok, but please check if it is working as intended

2024-09-16 12:44 UTC, lbenie requested changes
can you update the README as well, otherwise code looks good!

2024-09-16 12:45 UTC, lbenie commented
@all-contributors please add @stefanobartoletti for code

2024-09-17 13:08 UTC, stefanobartoletti commented
I updated the readme, it should be ok now

2024-09-18 12:56 UTC, lbenie approved these changes

2024-10-19 15:37 UTC, stefanobartoletti commented
@lbenie I'm not sure about how tests are managed here, can you provide some guidance?

2024-10-24 00:08 UTC, lbenie commented
Hey @stefanobartoletti 

yeah basically add some text like [so](https://github.com/lbenie/reading-time-estimator/blob/main/__tests__/reading-time-estimation.spec.ts#L5) and assert that it returns the appropriate estimation time and text!

2025-04-15 14:55 UTC, lbenie commented
Closing in favor of: https://github.com/lbenie/reading-time-estimator/pull/1860

2025-04-15 14:55 UTC, closed without merging